# Generated by Django 4.2.1 on 2023-05-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("family_name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
